---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: "3.6"

inputs: 
- name: auto-gate

run:
  path: sh
  dir: auto-gate
  args:
  - -ec
  - |
    echo "passed:"
    cat passed
    
    echo ""
    
    echo "metadata:"
    cat metadata