resource_types:
- name: gate-resource
  type: docker-image
  source:
    repository: meshcloud/gate-resource

gate-source: &gate-source
  git: 
    uri: git@github.com:Meshcloud/gate-resource-example.git
    private_key: ((github-key-readwrite))
    branch: gates

resources:
  - name: repo
    type: git
    source:
      uri: git@github.com:Meshcloud/gate-resource-example.git
      private_key: ((github-key-readwrite))
      branch: master

  - name: a-gate
    type: gate-resource
    source:
      <<: *gate-source
      gate: a

  - name: b-gate
    type: gate-resource
    source:
      <<: *gate-source
      gate: b

  - name: auto-gate
    type: gate-resource
    source:
      <<: *gate-source
      gate: autogate

jobs:
  - name: push-a
    plan:
    - get: repo
    - task: gen
      file: repo/ci/tasks/gen.yml
    - put: a-gate
      params:
        item_file: gen/*

  - name: fetch
    plan:
      - get: a-gate
        trigger: true
      - get: b-gate
        trigger: true
      - get: auto-gate
        trigger: true